export const ADD_STUDENT_START = 'ADD_STUDENT_START';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';

export const ADD_TEAM_START = 'ADD_TEAM_START';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';

export const FETCH_TEAMS_START = 'FETCH_TEAMS_START';
export const FETCH_TEAMS_FAIL = 'FETCH_TEAMS_FAIL';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';

export const GET_SELECTED_TEAM = 'GET_SELECTED_TEAM';
